export const SKILLS = [
  'AI',
  'Machine Learning',
  'Web Development',
  'Mobile Development',
  'UI/UX Design',
  'Data Science',
  'Blockchain',
  'Cloud Computing',
  'DevOps',
  'Cybersecurity',
  'IoT',
  'AR/VR',
  'Game Development',
  'Digital Marketing',
  'Product Management',
  'Business Analysis',
  'Software Architecture',
  'Full Stack Development',
  'Frontend Development',
  'Backend Development',
  'Database Design',
  'API Development',
  'Testing & QA',
  'Technical Writing',
  'Project Management',
] as const

export const INDUSTRIES = [
  'Technology',
  'Healthcare',
  'Finance',
  'Education',
  'Entertainment',
  'E-commerce',
  'Real Estate',
  'Manufacturing',
  'Transportation',
  'Energy',
  'Agriculture',
  'Retail',
  'Media',
  'Travel',
  'Food & Beverage',
  'Sports',
  'Fashion',
  'Gaming',
  'Social Impact',
  'Environmental',
  'Automotive',
  'Telecommunications',
  'Aerospace',
  'Biotechnology',
  'Consulting',
] as const 